### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by chel0** [asaafan/CSurfer#3]
I cannot get this to work. I have a straightforward anti-CSRF token in JSON string format (i.e. "parameter name":"Parameter value"). Each response contains a newly updated TOKEN which should be used in the next request. I have set the regex to "TOKEN":"(.*?)"} and when I run active scanner it does not update the token from the previous response. Is the issue with the JSON format or have you any idea?

**Comment by asaafan** [comment]
Are you using the correct regex match group configuration (one based not zero based)? Are you escaping the double quotes in the expression? 

Also, you can try using it in repeater first while trace debugging is enabled to see if the plugin is working.

**Comment by mavensecurity** [comment]
I'm changing my tune and revoking my prior comment about CSurfer not working.  CSurfer does work (in my case).  Two reasons I had trouble with CSurfer: 

1) I was using Intruder which by default is multi-threaded.  
2) The second issue was I accidentally had turned off the default Session Handling Rules under Burp Options that track cookie jar changes for various components (such as Intruder).  

When I fixed those two things I can see CSurfer is working.

My only suggestion is to change the default regex (of course) but the default sets a bad example for others in it is too greedy in the frist wild card:

.TOKEN"._value="(._?)">

So it could match some other parameter's "value" component.  In short, technically I think it should be:

.TOKEN" value="(.*?)">

Or perhaps:

.TOKEN"._?value="(._?)">

**Comment by asaafan** [comment]
Thanks for the suggestion.
